### ISSUE TITLE
aimbot sometimes ineffective

### ISSUE THREAD

**Issue by dsbingbong** [IceHacks/KrunkerCheatInjector#34]
the aimbot is able to hit some shots, or kill some people, but is ineffective most of the time - shots dont register even tho aimbot is firing and hitting people

**Comment by IceHacks** [comment]
[REDACTED]

I thought this was my surviv cheat lol. Try disabling aim at heads. As for shots not registering even though it hit someone. I don't believe that. I think it's just missing.

**Comment by IceHacks** [comment]
Although after playing a while it does seem to be doing that.

**Comment by dsbingbong** [comment]
ok ill try again thanks

**Comment by UglyzHacks** [comment]
Can you make a triggerbot please? If you lay your crosshair on somebody, it auto shoots. And can you make an esp toggle to turn it off/on? Also can you make the aimbot more smoother instead of it moving like jaggity? By jaggity i mean like its moving like 5 pixels everytime it aims at people. I also have a question, what is auto sights? Thank you for your time.
